# Generated by Django 4.2.7 on 2024-02-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='descricption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
